### ISSUE TITLE
counter_cache

### ISSUE THREAD

**Issue by kirillsalykin** [tcocca/acts_as_follower#38]
Hi, 

it would be great to have counter_cache similar to https://github.com/grimen/is_reviewable#caching

Thanks!

**Comment by u2** [comment]
But, if the user has many type `followable`, and I want to use `counter_cache` for every type.
https://github.com/rails/rails/issues/16407

**Comment by u2** [comment]
http://stackoverflow.com/questions/15725386/rails-has-many-through-polymorphic-counter-cache
> 
My suggestion would be to manually increment or decrement your counter cache in an after_commit callback so that you can test if the record was persisted and it updates outside of the transaction. This is because it will make your code more explicit, and less mysterious on how and when the cache is updated or invalidated.

Also manually updating the cache gives you extra flexibility if for example you wanted to give some users more authority when they agree or disagree with a comment (e.g. karma systems).

**Comment by u2** [comment]
```
class User < ActiveRecord::Base
  ...
  acts_as_followable
  ...
end

class Book < ActiveRecord::Base
  ...
  acts_as_followable
  ...
end
```
maybe the counter cache would be like 
```
class Book < ActiveRecord::Base
  ...
  acts_as_followable, counter_cache:  { user: :book_counter }
  ...
end
```

**Comment by magico** [comment]
Did anyone find a better solution for counter caching multiple followable types?
